//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iassetTechnicalTest.GlobalWeatherServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="GlobalWeatherServiceReference.GlobalWeatherSoap")]
    public interface GlobalWeatherSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetWeather", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        iassetTechnicalTest.GlobalWeatherServiceReference.GetWeatherResponse GetWeather(iassetTechnicalTest.GlobalWeatherServiceReference.GetWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<iassetTechnicalTest.GlobalWeatherServiceReference.GetWeatherResponse> GetWeatherAsync(iassetTechnicalTest.GlobalWeatherServiceReference.GetWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCitiesByCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        iassetTechnicalTest.GlobalWeatherServiceReference.GetCitiesByCountryResponse GetCitiesByCountry(iassetTechnicalTest.GlobalWeatherServiceReference.GetCitiesByCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetCitiesByCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<iassetTechnicalTest.GlobalWeatherServiceReference.GetCitiesByCountryResponse> GetCitiesByCountryAsync(iassetTechnicalTest.GlobalWeatherServiceReference.GetCitiesByCountryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWeather", WrapperNamespace="http://www.webserviceX.NET", IsWrapped=true)]
    public partial class GetWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=0)]
        public string CityName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=1)]
        public string CountryName;
        
        public GetWeatherRequest() {
        }
        
        public GetWeatherRequest(string CityName, string CountryName) {
            this.CityName = CityName;
            this.CountryName = CountryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWeatherResponse", WrapperNamespace="http://www.webserviceX.NET", IsWrapped=true)]
    public partial class GetWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=0)]
        public string GetWeatherResult;
        
        public GetWeatherResponse() {
        }
        
        public GetWeatherResponse(string GetWeatherResult) {
            this.GetWeatherResult = GetWeatherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCitiesByCountry", WrapperNamespace="http://www.webserviceX.NET", IsWrapped=true)]
    public partial class GetCitiesByCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=0)]
        public string CountryName;
        
        public GetCitiesByCountryRequest() {
        }
        
        public GetCitiesByCountryRequest(string CountryName) {
            this.CountryName = CountryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCitiesByCountryResponse", WrapperNamespace="http://www.webserviceX.NET", IsWrapped=true)]
    public partial class GetCitiesByCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webserviceX.NET", Order=0)]
        public string GetCitiesByCountryResult;
        
        public GetCitiesByCountryResponse() {
        }
        
        public GetCitiesByCountryResponse(string GetCitiesByCountryResult) {
            this.GetCitiesByCountryResult = GetCitiesByCountryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GlobalWeatherSoapChannel : iassetTechnicalTest.GlobalWeatherServiceReference.GlobalWeatherSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlobalWeatherSoapClient : System.ServiceModel.ClientBase<iassetTechnicalTest.GlobalWeatherServiceReference.GlobalWeatherSoap>, iassetTechnicalTest.GlobalWeatherServiceReference.GlobalWeatherSoap {
        
        public GlobalWeatherSoapClient() {
        }
        
        public GlobalWeatherSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GlobalWeatherSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalWeatherSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalWeatherSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public iassetTechnicalTest.GlobalWeatherServiceReference.GetWeatherResponse GetWeather(iassetTechnicalTest.GlobalWeatherServiceReference.GetWeatherRequest request) {
            return base.Channel.GetWeather(request);
        }
        
        public System.Threading.Tasks.Task<iassetTechnicalTest.GlobalWeatherServiceReference.GetWeatherResponse> GetWeatherAsync(iassetTechnicalTest.GlobalWeatherServiceReference.GetWeatherRequest request) {
            return base.Channel.GetWeatherAsync(request);
        }
        
        public iassetTechnicalTest.GlobalWeatherServiceReference.GetCitiesByCountryResponse GetCitiesByCountry(iassetTechnicalTest.GlobalWeatherServiceReference.GetCitiesByCountryRequest request) {
            return base.Channel.GetCitiesByCountry(request);
        }
        
        public System.Threading.Tasks.Task<iassetTechnicalTest.GlobalWeatherServiceReference.GetCitiesByCountryResponse> GetCitiesByCountryAsync(iassetTechnicalTest.GlobalWeatherServiceReference.GetCitiesByCountryRequest request) {
            return base.Channel.GetCitiesByCountryAsync(request);
        }
    }
}
